Repository terraform-redhat/terraform-rhcs-rosa-hcp, pull requests merged in 2025-08, with the labels that each got.

#83 Changing data source aws_region.current.name to aws_region.current.re…
  modules/oidc-config-and-provider/main.tf
  modules/rosa-cluster-hcp/main.tf
  modules/vpc/main.tf
Labels: approved, lgtm, ok-to-test

#86 OCM-17727 | fix: Bump hashicorp/aws to >5.4 and generate docs
  Makefile
  modules/account-iam-resources/README.md
  modules/account-iam-resources/versions.tf
  modules/idp/README.md
  modules/machine-pool/README.md
  modules/operator-roles/README.md
  modules/rosa-cluster-hcp/README.md
Labels: approved, lgtm, ok-to-test

#90 OCM-17727 | fix: Make AWS provider version gated >6.0
  modules/account-iam-resources/README.md
  modules/account-iam-resources/versions.tf
Labels: approved, lgtm

#91 OCM-17786 | fix: Adds the domain_prefix variable to the ROSA HCP module
  README.md
  main.tf
  modules/account-iam-resources/README.md
  modules/idp/README.md
  modules/machine-pool/README.md
  modules/operator-roles/README.md
  modules/rosa-cluster-hcp/README.md
  modules/rosa-cluster-hcp/main.tf
  modules/rosa-cluster-hcp/variables.tf
  variables.tf
Labels: lgtm, ok-to-test
